### ISSUE TITLE
📝Change Documentation

### ISSUE THREAD

**Issue by kaaax0815** [SkyDonald/spdl-core#1]
`Property 'setCredentials' does not exist on type 'typeof spdl'.`

There is no way to login with Client ID or Secret

**Comment by kaaax0815** [comment]
@SkyDonald I saw you are using [`spotify-url-info`](https://www.npmjs.com/package/spotify-url-info) which doesnt need login, please change the documentation then

**Comment by SkyDonald** [comment]
Done

**Comment by kaaax0815** [comment]
@SkyDonald why are the typings not uploaded to github?
